In [14]:
import pandas as pd
import numpy as np
data=[20,30,40,50]
ds=pd.Series(data)
print(ds)

ds1=pd.Series(np.array([10,20,30]))
print(ds1)

ds2=pd.Series(range(1,6))
print(ds2)

ds3=pd.Series({'a':20,'b':25,'c':30})
print(ds3)

ds4=pd.Series([20,30,40,50],index=['A','B','C','D'])
print(ds4)

0    20
1    30
2    40
3    50
dtype: int64
0    10
1    20
2    30
dtype: int32
0    1
1    2
2    3
3    4
4    5
dtype: int64
a    20
b    25
c    30
dtype: int64
A    20
B    30
C    40
D    50
dtype: int64

In [18]:
import pandas as pd
data={'name':['A','B','C','D'],
     'City':['Abd','surat','baroda','rajkot'],
     'Div':['D1','D2','D3','D4'],
     'Marks':[400,300,200,100]}
ds=pd.DataFrame(data)
print(ds)

  name    City Div  Marks
0    A     Abd  D1    400
1    B   surat  D2    300
2    C  baroda  D3    200
3    D  rajkot  D4    100

In [20]:
import pandas as pd
d=[['d1',20],['d2',30],['d3',40]]
ds1=pd.DataFrame(d,columns=['div','marks'],index=['A','B','C'])
print(ds1)

  div  marks
A  d1     20
B  d2     30
C  d3     40

In [29]:
import pandas as pd
s1=pd.Series([10,20,30])
s2=pd.Series([100,200,300])
ds1=pd.DataFrame({'col1':s1,'col2':s2})
print(ds1)

   col1  col2
0    10   100
1    20   200
2    30   300

In [30]:
ds=pd.DataFrame()
print(ds)

Empty DataFrame
Columns: []
Index: []

In [8]:
import pandas as pd

df=pd.read_csv('car.csv')
print(df)
ds1.to_csv('csv1.csv')
ds1.info()
print(ds1)

           Car       Model  Volume  Weight  CO2  Unnamed: 5
0       Toyota        Aygo    1000     790   99         NaN
1   Mitsubishi  Space Star    1200    1160   95         NaN
2        Skoda      Citigo    1000     929   95         NaN
3         Fiat         500     900     865   90         NaN
4         Mini      Cooper    1500    1140  105         NaN
5           VW         Up!    1000     929  105         NaN
6        Skoda       Fabia    1400    1109   90         NaN
7     Mercedes     A-Class    1500    1365   92         NaN
8         Ford      Fiesta    1500    1112   98         NaN
9         Audi          A1    1600    1150   99         NaN
10     Hyundai         I20    1100     980   99         NaN
11      Suzuki       Swift    1300     990  101         NaN
12        Ford      Fiesta    1000    1112   99         NaN
13       Honda       Civic    1600    1252   94         NaN
14      Hundai         I30    1600    1326   97         NaN
15        Opel       Astra    1600    1330   97         NaN
16         BMW           1    1600    1365   99         NaN
17       Mazda           3    2200    1280  104         NaN
18       Skoda       Rapid    1600    1119  104         NaN
19        Ford       Focus    2000    1328  105         NaN
20        Ford      Mondeo    1600    1584   94         NaN
21        Opel    Insignia    2000    1428   99         NaN
22    Mercedes     C-Class    2100    1365   99         NaN
23       Skoda     Octavia    1600    1415   99         NaN
24       Volvo         S60    2000    1415   99         NaN
25    Mercedes         CLA    1500    1465  102         NaN
26        Audi          A4    2000    1490  104         NaN
27        Audi          A6    2000    1725  114         NaN
28       Volvo         V70    1600    1523  109         NaN
29         BMW           5    2000    1705  114         NaN
30    Mercedes     E-Class    2100    1605  115         NaN
31       Volvo        XC70    2000    1746  117         NaN
32        Ford       B-Max    1600    1235  104         NaN
33         BMW           2    1600    1390  108         NaN
34        Opel      Zafira    1600    1405  109         NaN
35    Mercedes         SLK    2500    1395  120         NaN
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    object
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64
 7   origin        398 non-null    int64
 8   car name      398 non-null    object
dtypes: float64(3), int64(4), object(2)
memory usage: 28.1+ KB
      mpg  cylinders  displacement horsepower  weight  acceleration  \
0    18.0          8         307.0        130    3504          12.0
1    15.0          8         350.0        165    3693          11.5
2    18.0          8         318.0        150    3436          11.0
3    16.0          8         304.0        150    3433          12.0
4    17.0          8         302.0        140    3449          10.5
..    ...        ...           ...        ...     ...           ...
393  27.0          4         140.0         86    2790          15.6
394  44.0          4          97.0         52    2130          24.6
395  32.0          4         135.0         84    2295          11.6
396  28.0          4         120.0         79    2625          18.6
397  31.0          4         119.0         82    2720          19.4

     model year  origin                   car name
0            70       1  chevrolet chevelle malibu
1            70       1          buick skylark 320
2            70       1         plymouth satellite
3            70       1              amc rebel sst
4            70       1                ford torino
..          ...     ...                        ...
393          82       1            ford mustang gl
394          82       2                  vw pickup
395          82       1              dodge rampage
396          82       1                ford ranger
397          82       1                 chevy s-10

[398 rows x 9 columns]

In [40]:
%%writefile 'd1.csv'
name,div,marks
a,d1,20
b,d2,30
c,d3,40

Overwriting d1.csv

In [67]:
import pandas as pd
data={'name':['A','B','C','D'],
     'City':['Abd','surat','baroda','rajkot'],
     'Div':['D1','D2','D3','D4'],
     'Marks':[400,300,200,100]}
ds=pd.DataFrame(data)
print(ds)
print()
ds.set_index('Div')

  name    City Div  Marks
0    A     Abd  D1    400
1    B   surat  D2    300
2    C  baroda  D3    200
3    D  rajkot  D4    100

    name    City  Marks
Div
D1     A     Abd    400
D2     B   surat    300
D3     C  baroda    200
D4     D  rajkot    100

In [68]:
ds.reset_index(inplace=True)
ds

   index name    City Div  Marks
0      0    A     Abd  D1    400
1      1    B   surat  D2    300
2      2    C  baroda  D3    200
3      3    D  rajkot  D4    100

In [69]:
ds=pd.read_csv('car.csv')
type(ds)

pandas.core.frame.DataFrame

In [80]:
ds.head(7)
#ds.tail(10)
ds.sample(4)
ds.columns

Index(['Car', 'Model', 'Volume', 'Weight', 'CO2', 'Unnamed: 5'], dtype='object')

In [15]:
import pandas as pd
ds1=pd.read_csv("auto-mpg.csv")
ds1.info()
print(ds1)
ds1.describe()
ds1.describe(include="all")
ds1.describe(percentiles=[0.37,0.85])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    object
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64
 7   origin        398 non-null    int64
 8   car name      398 non-null    object
dtypes: float64(3), int64(4), object(2)
memory usage: 28.1+ KB
      mpg  cylinders  displacement horsepower  weight  acceleration  \
0    18.0          8         307.0        130    3504          12.0
1    15.0          8         350.0        165    3693          11.5
2    18.0          8         318.0        150    3436          11.0
3    16.0          8         304.0        150    3433          12.0
4    17.0          8         302.0        140    3449          10.5
..    ...        ...           ...        ...     ...           ...
393  27.0          4         140.0         86    2790          15.6
394  44.0          4          97.0         52    2130          24.6
395  32.0          4         135.0         84    2295          11.6
396  28.0          4         120.0         79    2625          18.6
397  31.0          4         119.0         82    2720          19.4

     model year  origin                   car name
0            70       1  chevrolet chevelle malibu
1            70       1          buick skylark 320
2            70       1         plymouth satellite
3            70       1              amc rebel sst
4            70       1                ford torino
..          ...     ...                        ...
393          82       1            ford mustang gl
394          82       2                  vw pickup
395          82       1              dodge rampage
396          82       1                ford ranger
397          82       1                 chevy s-10

[398 rows x 9 columns]

,mpg,cylinders,displacement,weight,acceleration,model year,origin
count,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000
mean,23.514573,5.454774,193.425879,2970.424623,15.568090,76.010050,1.572864
std,7.815984,1.701004,104.269838,846.841774,2.757689,3.697627,0.802055
min,9.000000,3.000000,68.000000,1613.000000,8.000000,70.000000,1.000000
37%,19.378000,4.000000,120.890000,2505.340000,14.500000,74.000000,1.000000
50%,23.000000,4.000000,148.500000,2803.500000,15.500000,76.000000,1.000000
85%,32.245000,8.000000,318.000000,4067.650000,18.500000,80.450000,3.000000
max,46.600000,8.000000,455.000000,5140.000000,24.800000,82.000000,3.000000

In [16]:
import pandas as pd
d={'name':['dustin','max','011','lucas'],'power':[120,134,10000,212],
  'average':[20.43,42.34,39.32,23.12]}

In [18]:
ds=pd.DataFrame(d)
print(ds)

     name  power  average
0  dustin    120    20.43
1     max    134    42.34
2     011  10000    39.32
3   lucas    212    23.12

In [19]:
print(ds.index)

RangeIndex(start=0, stop=4, step=1)

In [21]:
print(ds['power'])

0      120
1      134
2    10000
3      212
Name: power, dtype: int64

In [25]:
print(ds[['name','power']])

     name  power
0  dustin    120
1     max    134
2     011  10000
3   lucas    212

In [26]:
ds.loc[1]

name         max
power        134
average    42.34
Name: 1, dtype: object

In [27]:
ds.iloc[1]

name         max
power        134
average    42.34
Name: 1, dtype: object

In [29]:
ds.loc[0:3]

     name  power  average
0  dustin    120    20.43
1     max    134    42.34
2     011  10000    39.32
3   lucas    212    23.12

In [30]:
ds.iloc[0:3]

     name  power  average
0  dustin    120    20.43
1     max    134    42.34
2     011  10000    39.32

In [32]:
ds.loc[1,'name']

'max'

In [35]:
ds.iloc[1,0]

'max'

In [36]:
ds.loc[1,'name']='xyz'

In [39]:
ds.iloc[1,0]
ds.loc[1,'name']

'xyz'

In [40]:
ds.loc[:,'power']

0      120
1      134
2    10000
3      212
Name: power, dtype: int64

In [55]:
ds.loc[4]=['abc',232,24,99]
ds['fight']=[12,23,13,34,34]

ValueError: Must have equal len keys and value when setting with an iterable

In [50]:
ds.loc[:,:]

     name  power  average  fight
0  dustin    120    20.43     12
1     xyz    134    42.34     23
2     011  10000    39.32     13
3   lucas    212    23.12     34
4     abc    232    24.00     34

In [51]:
ds.loc[:,'strenth']=[24,45,676,67,56]

In [52]:
print(ds)

     name  power  average  fight  strenth
0  dustin    120    20.43     12       24
1     xyz    134    42.34     23       45
2     011  10000    39.32     13      676
3   lucas    212    23.12     34       67
4     abc    232    24.00     34       56

In [53]:
ds['asd']='good'

In [54]:
print(ds)

     name  power  average  fight  strenth   asd
0  dustin    120    20.43     12       24  good
1     xyz    134    42.34     23       45  good
2     011  10000    39.32     13      676  good
3   lucas    212    23.12     34       67  good
4     abc    232    24.00     34       56  good

In [58]:
ds.loc[ds['power']<150,'asd']='avg'

In [59]:
print(ds)

     name  power  average  fight  strenth   asd
0  dustin    120    20.43     12       24   avg
1     xyz    134    42.34     23       45   avg
2     011  10000    39.32     13      676  good
3   lucas    212    23.12     34       67  good
4     abc    232    24.00     34       56  good

# Data Cleaning

remove null values

In [96]:
import pandas as pd
df=pd.read_csv('sales_data.csv')
print(df)

       name region    sales  expenses
0   William    NaN  50000.0   42000.0
1      Emma  North  52000.0   43000.0
2     Sofia   East      NaN       NaN
3    Markus    NaN      NaN       NaN
4    Edward   West  42000.0   38000.0
5    Thomas   West  72000.0   39000.0
6     Ethan  South  49000.0   42000.0
7       NaN    NaN      NaN       NaN
8      Arun   West  67000.0   39000.0
9     Anika   East  65000.0   50000.0
10    Paulo  South  67000.0   45000.0

In [97]:
print(df.isna())

     name  region  sales  expenses
0   False    True  False     False
1   False   False  False     False
2   False   False   True      True
3   False    True   True      True
4   False   False  False     False
5   False   False  False     False
6   False   False  False     False
7    True    True   True      True
8   False   False  False     False
9   False   False  False     False
10  False   False  False     False

In [98]:
print(df.isna().sum())

name        1
region      3
sales       3
expenses    3
dtype: int64

In [99]:
df.dropna()#inplace=True

      name region    sales  expenses
1     Emma  North  52000.0   43000.0
4   Edward   West  42000.0   38000.0
5   Thomas   West  72000.0   39000.0
6    Ethan  South  49000.0   42000.0
8     Arun   West  67000.0   39000.0
9    Anika   East  65000.0   50000.0
10   Paulo  South  67000.0   45000.0

In [106]:
df.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [101]:
df.dropna(thresh=2)

       name region    sales  expenses
0   William    NaN  50000.0   42000.0
1      Emma  North  52000.0   43000.0
2     Sofia   East      NaN       NaN
4    Edward   West  42000.0   38000.0
5    Thomas   West  72000.0   39000.0
6     Ethan  South  49000.0   42000.0
8      Arun   West  67000.0   39000.0
9     Anika   East  65000.0   50000.0
10    Paulo  South  67000.0   45000.0

In [102]:
df.dropna(how='all')

       name region    sales  expenses
0   William    NaN  50000.0   42000.0
1      Emma  North  52000.0   43000.0
2     Sofia   East      NaN       NaN
3    Markus    NaN      NaN       NaN
4    Edward   West  42000.0   38000.0
5    Thomas   West  72000.0   39000.0
6     Ethan  South  49000.0   42000.0
8      Arun   West  67000.0   39000.0
9     Anika   East  65000.0   50000.0
10    Paulo  South  67000.0   45000.0

In [103]:
df.dropna(how='any')

      name region    sales  expenses
1     Emma  North  52000.0   43000.0
4   Edward   West  42000.0   38000.0
5   Thomas   West  72000.0   39000.0
6    Ethan  South  49000.0   42000.0
8     Arun   West  67000.0   39000.0
9    Anika   East  65000.0   50000.0
10   Paulo  South  67000.0   45000.0

In [108]:
df.dropna(subset=['sales','expenses'])

       name region    sales  expenses
0   William    NaN  50000.0   42000.0
1      Emma  North  52000.0   43000.0
4    Edward   West  42000.0   38000.0
5    Thomas   West  72000.0   39000.0
6     Ethan  South  49000.0   42000.0
8      Arun   West  67000.0   39000.0
9     Anika   East  65000.0   50000.0
10    Paulo  South  67000.0   45000.0

In [113]:
df['sales'].fillna(12)
df['sales'].fillna(df['sales'].mean())

0     50000.0
1     52000.0
2     58000.0
3     58000.0
4     42000.0
5     72000.0
6     49000.0
7     58000.0
8     67000.0
9     65000.0
10    67000.0
Name: sales, dtype: float64

In [115]:
df.fillna(1)

       name region    sales  expenses
0   William      1  50000.0   42000.0
1      Emma  North  52000.0   43000.0
2     Sofia   East      1.0       1.0
3    Markus      1      1.0       1.0
4    Edward   West  42000.0   38000.0
5    Thomas   West  72000.0   39000.0
6     Ethan  South  49000.0   42000.0
7         1      1      1.0       1.0
8      Arun   West  67000.0   39000.0
9     Anika   East  65000.0   50000.0
10    Paulo  South  67000.0   45000.0